steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'ARM'
    subscriptionName: 'd809edec-cbb5-4c01-ba88-90d9f114a718'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'MunichTest_lakshmi'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'createazurestorage/azuredeploy.json'
    deploymentMode: 'Incremental'